server:
  port:9000

spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

accounts:
  message: "Welcome to Card Microservice - Production"
  contactDetails:
    name: "Kajal - Production"
    email: "kajal.singh@gmail.com"
    mobile: 88998899889
  contributors:
    - "123"
    - "XYZ"
