server:
  port:9000


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "prod"

build:
  version: "3.0"


accounts:
  message: "Welcome to Card Microservice - Development"
  contactDetails:
    name: "Kajal"
    email: "kajal.singh@gmail.com"
    mobile: 88998899889
  contributors:
    - "123"
    - "XYZ"
