spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"


accounts:
  message: "Welcome to Account Microservice - QA application"
  contactDetails:
    name: "Rahul Ali"
    email: "rahul.singh@gmail.com"
    mobile: 7536064424
  contributors:
    - "Rahul"
    - "Nickel"
